### ISSUE TITLE
Can't install from conda-forge

### ISSUE THREAD

**Issue by sparsecoder** [QuantStack/xtensor-io#16]
I get the following error when trying to install through anaconda. I'm using linux. I also tried building from source, but when I run the example in the docs to load an image the kernel crashes (in jupyter notebook). After restarting the notebook server I get compile errors when ximage is `#included`. I haven't changed the cmake settings.
```
(cling)$ conda install xtensor-io -c QuantStack
Fetching package metadata .............
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - xtensor-io -> libsndfile
  - xtensor-io -> openimageio -> libwebp
```

**Comment by sparsecoder** [comment]
This seems to work
`conda install xtensor-io -c QuantStack -c conda-forge`

**Comment by wolfv** [comment]
Do you want to make a PR? Otherwise I'll edit the docs tomorrow to reflect that.

**Comment by wolfv** [comment]
I've added `-c conda-forge` to the Readme.
Thanks for reporting this issue.
