### ISSUE TITLE
Incorrect shape and strides after load_image()

### ISSUE THREAD

**Issue by ukoethe** [QuantStack/xtensor-io#22]
ximage-io claims to use the shape convention `WIDTH x HEIGHT x CHANNELS` (see http://xtensor-io.readthedocs.io/en/latest/api_reference.html#images) along with the usual c-order strides (increasing from back to front). However, this is **wrong**. 

All file formats store images such that the WIDTH axis has smaller stride than the HEIGHT axis, and *xtensor-io reads the memory unchanged*. This means that the shape must be `HEIGHT x WIDTH x CHANNELS` with corresponding strides. All other libraries that follow the c-order convention use this shape, see for example scikit-image. You can easily verify the error with a simple program:
```c++
        auto in  = xt::load_image("color_image.tif");
        for(int y=0; y<in.shape()[1]; ++y)
        {
            in(100, y, 1) = 255;
        }
        xt::dump_image("result.tif", in);
```
This should draw a vertical line, but actually draws a horizontal one.

**Comment by ukoethe** [comment]
PS: This is also the reason why the result of `grayscale_erosion()` you showed on gitter last week looked totally off.

**Comment by ukoethe** [comment]
> PS: please try to keep the discussion positive.

What exactly are you referring to? "Showstopper" meant to say that the library is unusable before the issue has been fixed, which I really believe is true.

**Comment by SylvainCorlay** [comment]
>> PS: please try to keep the discussion positive.
> 
> What exactly are you referring to? "Showstopper" meant to say that the library is unusable before the issue has been fixed, which I really believe is true.

You are absolutely right this is a very serious bug, and it is great you are getting into this!

While I don't think at all the intention is bad, I felt it can come across as confrontational.

As you can see, we are working hard to solve any issue that comes up as people engage with us.
