### ISSUE TITLE
Feature request: Image resizing function

### ISSUE THREAD

**Issue by achbogga** [QuantStack/xtensor-io#34]
Hello @wolfv ,

I could not find any supported function for resampling an image. It would be nice to have this here preferably using bilinear interpolation.

Thanks,
Achyut

**Comment by wolfv** [comment]
We don't currently support this, but you could probably use the shipped OpenImageIO to implement a quick version yourself.

See attached (copied from https://people.cs.clemson.edu/~dhouse/courses/404/papers/openimageio.pdf) 
![screenshot from 2018-06-15 17-08-13](https://user-images.githubusercontent.com/885054/41475359-e9164b32-70be-11e8-964d-02b8a6a1b0db.png)

**Comment by wolfv** [comment]
(for openimageio example code, you can check out the ximage file in this repo

**Comment by wolfv** [comment]
This functionality is out of scope for `xtensor-io`.

However, in the future, it would be cool if someone developed a library for image manipulation with xtensor-io as a component, and using code from either OpenImageIO or xtensor.
