### ISSUE TITLE
Installation without SndFile

### ISSUE THREAD

**Issue by tdegeus** [QuantStack/xtensor-io#40]
For users who are not interested exporting sound files, it would be great if installation could be done without the `SndFile` dependency!

**Comment by tdegeus** [comment]
Likewise for `OpenImageIO`

**Comment by wolfv** [comment]
Hey, 

are you referring to the conda installation? Or is there an issue with the CMake? I think CMake should not have a problem when you don't have the dependencies installed. 

With conda, we might be able to use the build variants feature to add/remove things.

**Comment by tdegeus** [comment]
Sorry 😔.

I am referring to the CMake installation. The problem comes from line 66 onwards:

```cpp
find_package(OIIO REQUIRED)
find_package(ZLIB REQUIRED)
find_package(SndFile REQUIRED)
```

**Comment by wolfv** [comment]
Ok, yes, you're right, they should not be required.

**Comment by tdegeus** [comment]
Done.
