### ISSUE TITLE
Undeclared real_promote_type_t in ximage.hpp

### ISSUE THREAD

**Issue by nganhkhoa** [QuantStack/xtensor-io#52]
https://github.com/QuantStack/xtensor-io/blob/e71b6b9093ff4aea2650b65bb0d4b9f075f8f89b/include/xtensor-io/ximage.hpp#L150

`real_promote_type_t` is used, but no reference is found. This can be solved by adding

```c++
#include <xtl/xtype_traits.hpp>
```
and change the line referenced to:

```c++
using real_t = xtl::real_promote_type_t<value_type>;
```

**Comment by SylvainCorlay** [comment]
This is because you are using xtensor master instead of the latest release. Please use a tagged version of xtensor and this should work.
