### ISSUE TITLE
Heap corruption when reading npz under MSVC

### ISSUE THREAD

**Issue by zhihaoy** [QuantStack/xtensor-io#59]
Microsoft Visual Studio Community 2017 
Version 15.9.14
cl Version 19.16.27032.1 for x64

Compile the following trivial program `a.cc`

```c++
#include "xtensor-io/xnpz.hpp"

void f() { auto npz = xt::load_npz("test8.npz"); }

int main() {
  try {
    std::cout << "enter\n";
    f();
    std::cout << "leave\n";
  } catch (std::exception &ec) {
    std::cout << ec.what() << std::endl;
  }
}
```

with command

```
cl /EHsc /MDd /DEBUG /Od /I <your-miniconda-envs-envs>\Library\include <your-miniconda-envs-envs>\Library\lib\z.lib a.cc
```

Create a file `test8.npz` with more than 8 arrays, one of which larger than 50x50 under the current directory, then run `a.exe`

![image](https://user-images.githubusercontent.com/43971430/62002751-d719f700-b0d0-11e9-94bd-064cdaa32fd6.png)

1. The file `test\files\uncompressed.npz` is too small for revealing this.  We need about 10 entries.
2. Both `load_npz` overloads encounter the same issue.
3. The heap corruption is real.  If you replace `/MDd` (Debug CRT) with `/MD` (Release CRT), the program crashes.
4. The issue may have something to do with `detail::npy_file` (or some intermediate adapters) lifetime.  I rewrote a specialized function to immediately cast the return value of `detail::load_npy_file` and assign it to an `xarray`, that works fine.

**Comment by zhihaoy** [comment]
I should elaborate a little bit if it helps: although I titled the issue "heap corruption," but the root cause is more likely to be a stack corruption on a heap pointer.  In MSVC, if an object on stack finishes its lifetime (a temporary object, for example), other objects can overwrite its stack storage.  Other compilers do not do this but this is legal.  I suspect that a sanitizer can tell you more.

**Comment by wolfv** [comment]
This is an unrelated issue to your PR, right?

**Comment by zhihaoy** [comment]
Yes.  I couldn't figure this out in an hour, so I went ahead writing my own `load_npz`, which uses a vtable to map array names to callbacks that directly do `my_struct.member = detail::load_npy_file(stream).cast<double>();`, which doesn't have the issue.

**Comment by zhihaoy** [comment]
Now I know why my version works.  Only when `npy_file` is a (p)rvalue, `cast` takes away its [buffer ownership](https://github.com/QuantStack/xtensor/blob/master/include/xtensor/xnpy.hpp#L564-L565), and [xbuffer adaptors](https://github.com/QuantStack/xtensor/blob/master/include/xtensor/xbuffer_adaptor.hpp) faithfully deallocates with `std::allocator<char>::deallocate` rather than `delete` operator...
